services:
  web:
    container_name: bars-webapp
    build: .
    # depends_on: 
    #   db:
    #     condition: service_healthy
    env_file:
      - .dev.env
    ports:
      - 8080:3000

#   db:
#     image: postgres
#     restart: always
#     environment: 
#       - POSTGRES_USER = michatzis
#       - POSTGRES_PASSWORD = test123
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready"]
#         interval: 1s
#       timeout: 5s
#         retries: 3
#     ports:
#       - 8080:8080
#     volumes:
#       - db_vol: /var/lib/postgresql/data

# volumes:
#   db_vol:
  

