services:
  db:
    container_name: bars-db
    image: postgres:15.4-bookworm
    restart: always
    env_file:
      - .db.env
    healthcheck:
      # First '$'' escapes the second '$'. 
      # Hence, compose will not try to substitute
      test: pg_isready -U $$POSTGRES_USER
      interval: 1s
      timeout: 2s
      retries: 3
    ports:
      - 5000:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  admin:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 5001:8080
  
  web:
    container_name: bars-webapp
    build: .
    depends_on: 
      db:
        condition: service_healthy
    env_file:
      - .prod.env
      - .db.env
    expose:
      - 8000
    volumes:
      - static_volume:/home/ec2-user/app/bars-webapp/collectedstatic
  
  nginx:
    build: ./nginx
    ports: 
      - 80:80
      - 443:443
    depends_on:
      - web
    volumes:
      - static_volume:/home/ec2-user/app/bars-webapp/collectedstatic
      - /home/ec2-user/.acme.sh/thess-places.space_ecc:/home/ec2-user/.acme.sh/thess-places.space_ecc

volumes:
  pg_data:
    name: bars-data
  static_volume:
