openapi: 3.0.3
info:
  title: ''
  version: 0.0.0
paths:
  /api/bars/:
    get:
      operationId: api_bars_list
      tags:
      - api
      security:
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Bar'
          description: ''
    post:
      operationId: api_bars_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Bar'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Bar'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Bar'
        required: true
      security:
      - cookieAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bar'
          description: ''
  /api/bars/{id}/:
    get:
      operationId: api_bars_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this bar.
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bar'
          description: ''
    put:
      operationId: api_bars_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this bar.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Bar'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Bar'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Bar'
        required: true
      security:
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bar'
          description: ''
    patch:
      operationId: api_bars_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this bar.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedBar'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedBar'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedBar'
      security:
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bar'
          description: ''
    delete:
      operationId: api_bars_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this bar.
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - {}
      responses:
        '204':
          description: No response body
components:
  schemas:
    Bar:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        longitude:
          type: string
          format: decimal
          pattern: ^-?\d{0,1}(?:\.\d{0,5})?$
        latitude:
          type: string
          format: decimal
          pattern: ^-?\d{0,1}(?:\.\d{0,5})?$
      required:
      - id
      - latitude
      - longitude
    PatchedBar:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        longitude:
          type: string
          format: decimal
          pattern: ^-?\d{0,1}(?:\.\d{0,5})?$
        latitude:
          type: string
          format: decimal
          pattern: ^-?\d{0,1}(?:\.\d{0,5})?$
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
