/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Bar,
} from '../models';
import {
    BarFromJSON,
    BarToJSON,
} from '../models';

export interface BarsListRequest {
    type?: string;
}

/**
 * 
 */
export class BarsApi extends runtime.BaseAPI {

    /**
     */
    async barsListRaw(requestParameters: BarsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Bar>>> {
        const queryParameters: any = {};

        if (requestParameters.type !== undefined) {
            queryParameters['type'] = requestParameters.type;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/bars/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BarFromJSON));
    }

    /**
     */
    async barsList(requestParameters: BarsListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Bar>> {
        const response = await this.barsListRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
