/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BarType,
} from '../models';
import {
    BarTypeFromJSON,
    BarTypeToJSON,
} from '../models';

/**
 * 
 */
export class BarTypesApi extends runtime.BaseAPI {

    /**
     */
    async barTypesListRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<BarType>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/bar-types/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BarTypeFromJSON));
    }

    /**
     */
    async barTypesList(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<BarType>> {
        const response = await this.barTypesListRaw(initOverrides);
        return await response.value();
    }

}
