# Generated by Django 4.2.1 on 2023-07-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=5, max_digits=6, verbose_name="Longitude"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=5, max_digits=6, verbose_name="Latitude"
                    ),
                ),
            ],
        ),
    ]
