# Generated by Django 4.2.4 on 2023-09-28 10:30

import bars_app.aws_storage
import bars_app.models
from django.db import migrations, models
import functools


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BarType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Bar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature_type",
                    models.CharField(
                        choices=[("Point", "Point")], default="Point", max_length=20
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=10, verbose_name="Longitude"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=10, verbose_name="Latitude"
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("description", models.TextField(blank=True, max_length=120)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "tiny_thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=bars_app.aws_storage.MediaStorage,
                        upload_to=functools.partial(
                            bars_app.models.get_upload_path,
                            *(),
                            **{"img_type": "tiny_thumbnail"}
                        ),
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=bars_app.aws_storage.MediaStorage,
                        upload_to=functools.partial(
                            bars_app.models.get_upload_path,
                            *(),
                            **{"img_type": "thumbnail"}
                        ),
                    ),
                ),
                (
                    "image1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=bars_app.aws_storage.MediaStorage,
                        upload_to=functools.partial(
                            bars_app.models.get_upload_path,
                            *(),
                            **{"img_type": "image1"}
                        ),
                    ),
                ),
                (
                    "image2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=bars_app.aws_storage.MediaStorage,
                        upload_to=functools.partial(
                            bars_app.models.get_upload_path,
                            *(),
                            **{"img_type": "image2"}
                        ),
                    ),
                ),
                (
                    "image3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=bars_app.aws_storage.MediaStorage,
                        upload_to=functools.partial(
                            bars_app.models.get_upload_path,
                            *(),
                            **{"img_type": "image3"}
                        ),
                    ),
                ),
                (
                    "image4",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=bars_app.aws_storage.MediaStorage,
                        upload_to=functools.partial(
                            bars_app.models.get_upload_path,
                            *(),
                            **{"img_type": "image4"}
                        ),
                    ),
                ),
                (
                    "image5",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=bars_app.aws_storage.MediaStorage,
                        upload_to=functools.partial(
                            bars_app.models.get_upload_path,
                            *(),
                            **{"img_type": "image5"}
                        ),
                    ),
                ),
                ("bar_type", models.ManyToManyField(to="bars_app.bartype")),
            ],
            options={
                "ordering": ["last_modified"],
            },
        ),
    ]
