# Generated by Django 4.2.4 on 2023-09-07 08:07

import bars_app.aws_storage
import bars_app.models
from django.db import migrations, models
import functools


class Migration(migrations.Migration):
    dependencies = [
        ("bars_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bar",
            name="tiny_thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=bars_app.aws_storage.MediaStorage,
                upload_to=functools.partial(
                    bars_app.models.get_upload_path,
                    *(),
                    **{"img_type": "tiny_thumbnail"}
                ),
            ),
        ),
    ]
