# Generated by Django 4.2.1 on 2023-08-01 07:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("bars_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BarTypes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="bar",
            options={"ordering": ["last_modified"]},
        ),
        migrations.AddField(
            model_name="bar",
            name="Image URL",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="bar",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bar",
            name="description",
            field=models.TextField(default="", max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bar",
            name="feature_type",
            field=models.CharField(
                choices=[("Point", "Point")], default="Point", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="bar",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="bar",
            name="title",
            field=models.CharField(default="", max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bar",
            name="latitude",
            field=models.DecimalField(
                decimal_places=6, max_digits=8, verbose_name="Latitude"
            ),
        ),
        migrations.AlterField(
            model_name="bar",
            name="longitude",
            field=models.DecimalField(
                decimal_places=6, max_digits=8, verbose_name="Longitude"
            ),
        ),
        migrations.AddField(
            model_name="bar",
            name="bar_type",
            field=models.ManyToManyField(to="bars_app.bartypes"),
        ),
    ]
