# Generated by Django 4.2.1 on 2023-08-01 12:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bars_app", "0002_bartypes_alter_bar_options_bar_image_url_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bar",
            old_name="Image URL",
            new_name="image_url",
        ),
    ]
