# Generated by Django 4.2.1 on 2023-08-04 07:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bars_app", "0003_rename_image_url_bar_image_url"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BarTypes",
            new_name="BarType",
        ),
    ]
