# Generated by Django 4.2.1 on 2023-08-23 12:30

import bars_app.models
from django.db import migrations, models
import functools


class Migration(migrations.Migration):
    dependencies = [
        ("bars_app", "0004_rename_bartypes_bartype"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bar",
            name="image_url",
        ),
        migrations.AddField(
            model_name="bar",
            name="image1",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=functools.partial(
                    bars_app.models.get_upload_path, *(), **{"img_type": "image1"}
                ),
            ),
        ),
        migrations.AddField(
            model_name="bar",
            name="image2",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=functools.partial(
                    bars_app.models.get_upload_path, *(), **{"img_type": "image2"}
                ),
            ),
        ),
        migrations.AddField(
            model_name="bar",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=functools.partial(
                    bars_app.models.get_upload_path, *(), **{"img_type": "thumbnail"}
                ),
            ),
        ),
        migrations.AddField(
            model_name="bar",
            name="tiny_thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=functools.partial(
                    bars_app.models.get_upload_path,
                    *(),
                    **{"img_type": "tiny_thumbnail"}
                ),
            ),
        ),
        migrations.AlterField(
            model_name="bar",
            name="description",
            field=models.TextField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="bar",
            name="latitude",
            field=models.DecimalField(
                decimal_places=6, max_digits=10, verbose_name="Latitude"
            ),
        ),
        migrations.AlterField(
            model_name="bar",
            name="longitude",
            field=models.DecimalField(
                decimal_places=6, max_digits=10, verbose_name="Longitude"
            ),
        ),
    ]
