# Generated by Django 4.2.1 on 2023-08-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bars_app", "0004_rename_bartypes_bartype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bar",
            name="description",
            field=models.TextField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="bar",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bar",
            name="latitude",
            field=models.DecimalField(
                decimal_places=6, max_digits=10, verbose_name="Latitude"
            ),
        ),
        migrations.AlterField(
            model_name="bar",
            name="longitude",
            field=models.DecimalField(
                decimal_places=6, max_digits=10, verbose_name="Longitude"
            ),
        ),
    ]
