# Generated by Django 4.2.1 on 2023-08-11 11:12

import bars_app.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bars_app", "0005_alter_bar_description_alter_bar_image_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bar",
            name="image_url",
        ),
        migrations.AddField(
            model_name="bar",
            name="image1",
            field=models.ImageField(
                blank=True, null=True, upload_to=bars_app.models.get_upload_path
            ),
        ),
        migrations.AddField(
            model_name="bar",
            name="image2",
            field=models.ImageField(
                blank=True, null=True, upload_to=bars_app.models.get_upload_path
            ),
        ),
        migrations.AddField(
            model_name="bar",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to=bars_app.models.get_upload_path
            ),
        ),
        migrations.AddField(
            model_name="bar",
            name="tiny_thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to=bars_app.models.get_upload_path
            ),
        ),
    ]
