/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Bar
 */
export interface Bar {
    /**
     * 
     * @type {number}
     * @memberof Bar
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof Bar
     */
    longitude: string;
    /**
     * 
     * @type {string}
     * @memberof Bar
     */
    latitude: string;
}

/**
 * Check if a given object implements the Bar interface.
 */
export function instanceOfBar(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "longitude" in value;
    isInstance = isInstance && "latitude" in value;

    return isInstance;
}

export function BarFromJSON(json: any): Bar {
    return BarFromJSONTyped(json, false);
}

export function BarFromJSONTyped(json: any, ignoreDiscriminator: boolean): Bar {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'longitude': json['longitude'],
        'latitude': json['latitude'],
    };
}

export function BarToJSON(value?: Bar | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'longitude': value.longitude,
        'latitude': value.latitude,
    };
}

