/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { FeatureTypeEnum } from './FeatureTypeEnum';
import {
    FeatureTypeEnumFromJSON,
    FeatureTypeEnumFromJSONTyped,
    FeatureTypeEnumToJSON,
} from './FeatureTypeEnum';

/**
 * 
 * @export
 * @interface Bar
 */
export interface Bar {
    /**
     * 
     * @type {FeatureTypeEnum}
     * @memberof Bar
     */
    featureType?: FeatureTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof Bar
     */
    longitude: string;
    /**
     * 
     * @type {string}
     * @memberof Bar
     */
    latitude: string;
    /**
     * 
     * @type {string}
     * @memberof Bar
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof Bar
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof Bar
     */
    imageUrl?: string | null;
}

/**
 * Check if a given object implements the Bar interface.
 */
export function instanceOfBar(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "longitude" in value;
    isInstance = isInstance && "latitude" in value;
    isInstance = isInstance && "title" in value;

    return isInstance;
}

export function BarFromJSON(json: any): Bar {
    return BarFromJSONTyped(json, false);
}

export function BarFromJSONTyped(json: any, ignoreDiscriminator: boolean): Bar {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'featureType': !exists(json, 'feature_type') ? undefined : FeatureTypeEnumFromJSON(json['feature_type']),
        'longitude': json['longitude'],
        'latitude': json['latitude'],
        'title': json['title'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'imageUrl': !exists(json, 'image_url') ? undefined : json['image_url'],
    };
}

export function BarToJSON(value?: Bar | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'feature_type': FeatureTypeEnumToJSON(value.featureType),
        'longitude': value.longitude,
        'latitude': value.latitude,
        'title': value.title,
        'description': value.description,
        'image_url': value.imageUrl,
    };
}

