/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `Point` - Point
 * @export
 */
export const FeatureTypeEnum = {
    Point: 'Point'
} as const;
export type FeatureTypeEnum = typeof FeatureTypeEnum[keyof typeof FeatureTypeEnum];


export function FeatureTypeEnumFromJSON(json: any): FeatureTypeEnum {
    return FeatureTypeEnumFromJSONTyped(json, false);
}

export function FeatureTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeatureTypeEnum {
    return json as FeatureTypeEnum;
}

export function FeatureTypeEnumToJSON(value?: FeatureTypeEnum | null): any {
    return value as any;
}

