/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedBar
 */
export interface PatchedBar {
    /**
     * 
     * @type {number}
     * @memberof PatchedBar
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedBar
     */
    longitude?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedBar
     */
    latitude?: string;
}

/**
 * Check if a given object implements the PatchedBar interface.
 */
export function instanceOfPatchedBar(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchedBarFromJSON(json: any): PatchedBar {
    return PatchedBarFromJSONTyped(json, false);
}

export function PatchedBarFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedBar {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'longitude': !exists(json, 'longitude') ? undefined : json['longitude'],
        'latitude': !exists(json, 'latitude') ? undefined : json['latitude'],
    };
}

export function PatchedBarToJSON(value?: PatchedBar | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'longitude': value.longitude,
        'latitude': value.latitude,
    };
}

